-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Erstellungszeit: 23. Mai 2025 um 09:42
-- Server-Version: 10.4.32-MariaDB
-- PHP-Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `karteikarten`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `karten`
--

CREATE TABLE `karten` (
  `id` int(11) NOT NULL,
  `questen` text NOT NULL,
  `answer` text NOT NULL,
  `category` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Daten für Tabelle `karten`
--

INSERT INTO `karten` (`id`, `questen`, `answer`, `category`) VALUES
(1, 'Was ist ein Netzplan im Projektmanagement?', 'Der Netzplan hilft bei der Terminplannung von Projekten und stellt die Dauer von Vorängen im Gesamtprojekt grafisch dar.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(2, 'Was ist ein Gantt-Diagramm?', 'In einem Gantt-Diagramm werden alle Aktivitäten eines Projektes mit Hilfe einer horisantalen Zeitachse dargestellt Abhängigkeiten zwischen den einzehlnen Aktivitäten werden mit Hilfe  von Pfeilen  verdeutlicht. Vorteil: Sehr übersichtliche Darstellung für kleine und mittlere Projekte Nachteil: bei großer Anzahl von Aktivitäten wird die DDarstellung schnell unübersichtlich.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(3, 'Was versteht man unter dem Top-Down-Ansatz beim Projektstrukturplan?', 'Der Top-Down-Ansatz verfolgt das Ziel, dass der Weg vom Ganzem zum Detail führt. Das Gesamtprojekt wird  in mehrere Teilaufgaben zerlegt. Der Top-Down-Ansatz wird immer dann gewählt, wenn bereits Erfahrungen vorliegen mit ähnlichen Projekten oder die Inhalte des projektes aus vorherigen Projekten bereits bekannt sind.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(4, 'Was versteht man unter dem Begriff Bottom-Up-Ansatz beim Projektstrukturplan?', 'Der Bottom-Up-Ansatz verfolgt das Ziel, dass der Weg von Details zum Ganzen führt. abgegrenzte, detaillierte Teilprobleme gelöst werden, um dann mit deren Hilfe größere, darüberliegende Probleme zu lösen. Der Ansatz kommt bei sehr innovativen Lösungen zum Einsatz.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(5, 'Was versteht man unter dem 4-Phasen-Modell beim Projektmanagment?', 'das Model beschreibt die Phasen beim Projektmanagement. - Projektdefinition, Projektplannung, Projektdurchführung und Controlling, Projektabschluss. exestiert noch 5 Phasen-Modell, wo : 1. Phase - die Initiierung des Projekts ', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(6, 'Was bezeichnet man als kritischen Pfad beim Netzplan?', 'Kritischer Pfad ist der Weg von Anfang bis zum Ende aller Aktivitäten eines Netzplans, auf dem die Summe aller Pufferzeiten Null wird. Gesamtprojektdauer wird durch den kritischen Pfad bestimmt.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(7, 'Was versteht man unter Forming, Storming, Norming und Performing im Teambildungsprozess?', 'Forming: Das Team lernt sich kennen und ist noch unsicher in der Zusammenarbeit. Storming: Es gibt Konflikte und Meinungsverschiedenheiten, da unterschiedliche Arbeitsweisen aufeinandertreffen. Norming: Das Team findet gemeinsame Regeln und arbeitet besser zusammen. Performing: Das Team arbeitet effizient und harmonisch, um Ziele zu erreichen.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(8, 'Was bezeichnet man als Kick-Off-Meetinf?', 'Kick-off-Meeting findet vor dem Start der Durchführung statt. alle Mitglieder des Projektteams nehmen daran teil. Auftraggeber und weitere relevante Steakholder einbezogen werden.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(9, 'Was versteht man unter einer Meilenstein-Planung?', 'Das ist eine Form der Projektplannung die folgende Ziele verfolgt: Grobe Terminplannung, Meilsteine im Projekt transporent zu machen, Übersicht über Verzögerungen und möglichen Auswirkungen auf andere Termine sichtbar machen, Schaffen von Zwischenzielen zur Motivation der Mitarbeitenden', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(10, 'Welche Vorgehensmodelle solltest du im Projektmanagement, insbesondere in der Anwendungsentwicklung kennen?', 'klassische Modelle: Wasserfallmodell, V-Modell, Spiralmodell. Agile Modelle: Scrum, Kanban, Inkrementelles Vorgehensmodell.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(11, 'Erläutere die Vor-und Nachteile des Wasserfallmodells', 'Vorteile: Abgolge der Projektschritte klar erkenntlich, sehr einfache Nachverfolgung der Projektschritte möglisch, einfache Plannung und Kontrolle aller Projektphasen. \nNachteile: bei großen Projekten es ist schwierig zu Projektsbeginn alles im Detail festzulegen, Unflexibel, wenn sich Anforderungen während des Projektes ändern, Risiko bei unklaren Anforderungen, dass Ergebniss nicht den tatsächlichen Anforderungen entspricht.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(12, 'Was sind Bestandteile einer Risikoanalyse?', 'dazu gehören: die Risikobeurteilung, die Risikokommunikation, die Risikoklassifizierung und die Risikoprävention', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(13, 'Was versteht man unter dem Begriff Stakeholder?', 'dazu gehören alle, die interesse am Verlauf oder Ergebnis eines Prozesses, eines Projektes oder Investments haben. z.B auch Kunde oder Mitarbeitende die funktion von Stakeholdern einnehmen', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(14, 'Welches sind die Hauptziele der Datensicherheit?', 'Vertraulichkeit - Daten nur befugten Personen zur Verarbeitung zugänglich sind. Integrität - Daten sind korrekt, unverändert bzw. verlässlich. Verfügbarkeit - Verfügbarkeit und Erreichbarkeit aller Systeme sowie Verhinderung von Systemausfällen der Iuk-Systeme.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(15, 'Wie errechnet sich der Gewinn eines Unternehmens?', 'Der Gewinn eines Unternehmens berechnet sich anhand der Formel: GEWINN = ERLÖS - KOSTEN Die Erlöse sind alle Einnahmen, die durch Verkauf von Waren und Dienstleisungen entstehen. zu den Kosten zählen die variablen und fixen Kosten, wie Rohstoffkosten, Mietkosten sowie Personalkosten.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(16, 'Was versteht man unter einer Machbarkeitsanalyse?', 'Eine Machbarkeitsanalyse prüft, ob ein Projekt oder Vorhaben realisierbar ist. Dabei wird untersucht, ob es technisch, finanziell und zeitlich umsetzbar ist und ob die Ziele erreicht werden können. Es hilft, Risiken frühzeitig zu erkennen und Entscheidungen zu treffen.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(17, 'Was sind Ziele einer Machbarkeitsanalyse?', 'Überprüfung der Realisierbarkeit: Klärung, ob das Projekt technisch, finanziell und zeitlich möglich ist. Risikomanagement: Identifikation möglicher Risiken und Probleme, die auftreten könnten. Ressourcenplanung: Feststellung, welche Ressourcen (z. B. Personal, Technik, Geld) benötigt werden.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(18, 'Wie berechnet sich der Deckungsbeitrag bei Unternehmen?', ' Der Deckungsbeitrag ist der Beitrag, der zur Deckung der Fixkosten zur Verfügung steht (Deckungsbeitrag = Erlös - Variable Kosten)', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(19, 'Welche Arten von Äußerungen sind in einem Kundengespräch nicht förderlich?', ' Belehrungen, Killerphrasen wie : Das können nur wir!, Erzeugung von Druck, Termindruck auf Kunden, Konkurrenz diskreditieren', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(20, 'In welchem Softwaresystem werden in der Regel Supportanfragen verarbeitet?', '- Ticketing-System, User-Helpdesk-System, Service-Ticket-System und ähnliche. dabei geht es um Empfang, Bestätigung, Klassifizierung, Bearbeitung sowie die Pflege von Kundenanfragen in Form von Tickets bzw. Fällen/Cases. es kann per Telefon, per Mail, oder Online entgegengenommen werden.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(21, 'Nenne die Vorteile für ein User-Helpdesk-Ticketsystem.', '- Alle Anfragen werden an einem Ort gesammelt und können leichter verwaltet werden. - Jedes Ticket hat eine eindeutige ID, sodass der Status und die Bearbeitungshistorie jederzeit eingesehen werden können. -Anfragen können nach Priorität und Dringlichkeit sortiert und schnell an die zuständigen Personen weitergeleitet werden.', 'Planen, Vorbereiten und Durchführen von Arbeitsaufgaben'),
(22, 'Was versteht man unter dem Begriff volkswirtschaftliche Sektoren?', 'Man unterscheidet meist drei Hauptsektoren: Primärer Sektor: Rohstoffgewinnung (z. B. Landwirtschaft, Fischerei, Bergbau). Sekundärer Sektor: Industrie und Verarbeitung (z. B. Produktion, Bauwesen). Tertiärer Sektor: Dienstleistungen (z. B. Handel, Bildung, Gesundheitswesen). Jeder Sektor spielt eine wichtige Rolle in der Wirtschaft und trägt zum Gesamtwachstum bei.', 'Informieren und Beraten von Kunden und Kundinnen'),
(23, 'Was versteht man unter der Marktform des Monopols?', 'ist eine Marktform in der Marktwirtschaft, bei welcher nur ein Anbieter viele Nachfragen gegenübersteht oder umgekehrt. Der Monopolist kann weitergehend das Angebot ind den Preis am Markt bestimmen', 'Informieren und Beraten von Kunden und Kundinnen'),
(24, 'Wann spricht man in der Wirtschaft von einem Angebotsoligopol?', 'eine Marktform, die durch wenige Anbieter auf der einen Seite und durch viele Nachfrager auf der anderen Seite gekennzeichnet ist. Beispiel: Energiemarkt bzw. Mobilfunkmarkt.', 'Informieren und Beraten von Kunden und Kundinnen'),
(25, 'Was versteht man unter dem Begriff IT-Benchmarking?', 'IT-Benchmarking bedeutet, die Leistung von IT-Systemen, -Prozessen oder -Diensten zu messen und mit den anderen Unternehmen zu vergleichen. Ziel ist es, Schwächen zu erkennen und die eigene IT zu verbessern, indem man sieht, wie man im Vergleich abschneidet.', 'Informieren und Beraten von Kunden und Kundinnen'),
(26, 'Welche Kriterien müssen erfüllt sein für ein Marktgleichgewicht?', 'Wenn ein Zustand erreicht wird, in dem die angebotene Menge und die nachgefragte Menge nach Gütern übereinstimmen.', 'Informieren und Beraten von Kunden und Kundinnen'),
(27, 'Wann spricht man von einem Käufermarkt?', 'eine Marktsituation, in der sich die Käuferseite in der besseren Position gegenüber der Verkäuferseite befindet.z.B wenn das Angebot die Nachfrage deutlich übersteigt. Als Folge ist ein sinkender Preis zu beobachten, was zu sinkenden Umsätzen führt.', 'Informieren und Beraten von Kunden und Kundinnen'),
(28, 'Welche Aufgaben und Ziele verfolgen die betrieblichen Grundfunktionen?', 'dazu zählen: -Beschafuung: Einkauf von Roh und Betriebsstoffen.  -Produktion: Herstellen von Materiallen.  -Absatz/Vertrieb: Verkauf der produzierten Waren. - Finanzierung: alle Prozesse, die mit finanzielle Versorgung, Steuerung stehen.', 'Informieren und Beraten von Kunden und Kundinnen'),
(29, 'Welche Merkmale besitzt eine Europäische Gesellschaft?', '- Sie ist eine Kapitalgesellschaft - Das Mindestkapital beträgt 120.000 Euro - besitzt eine eigene Rechtspersönlichkeit', 'Informieren und Beraten von Kunden und Kundinnen'),
(30, 'Welche Kriterien müssen für die Marktform des Polypols erfüllt sein?', 'Das Polypol gilt als die bestmöglische Marktform der Marktwirtschaft, bei der sich viele Anbieter und viele Nachfrager gegenüberstehen und miteinander in Konkurrenz treten.', 'Informieren und Beraten von Kunden und Kundinnen'),
(31, 'Welche Unternehmensformen sind in Deutschland Personengesellschaften?', 'GbR (Gesellschaft bürgerlichen Rechts) OHG (Offene Handelsgesellschaft) KG (Kommanditgesellschaft)', 'Informieren und Beraten von Kunden und Kundinnen'),
(32, 'Welche Bedingungen und welche Haftungsregeln gelten bei einer offenen Handelsgesellschaft -OHG?', '1. es müssen mindestens zwei Personen (Einzelpersonen oder Unternehmen) zusammenarbeiten. 2. Die OHG muss ein Handelsgewerbe betreiben. 3. Der Gesellschaftsvertrag regelt, wie die OHG geführt wird. Alle Gesellschafter haften unbeschränkt mit ihrem privaten Vermögen für die Schulden der OHG.', 'Informieren und Beraten von Kunden und Kundinnen'),
(33, 'Welche Sachverhalte können das Betriebsergebniss positiv beeinflussen?', 'es gibt folgende Möglichkeiten: Wareneinkauf optimieren, Herstellungskosten senken, Reduzierung der Werbkosten, Personalkosten reduzieren, allgemeine Verwaltungskosten minimieren, Fixkosten mindern.', 'Informieren und Beraten von Kunden und Kundinnen'),
(34, 'Unternehmen richten Ihre Produkte mit Hilfe von Marketingmaßnamen nach den Kundenwünschen aus. Welchem Zweg dienen in diesem Zusammenhang Kundenbefragungen?', 'durch Kundenbefragungen können zentrale Punkte wie Kundenzufriedenheit, Trends, das Image des Unternehmens, Marktposition und der Erfolg von Werbmaßnamen beantwortet werden.', 'Informieren und Beraten von Kunden und Kundinnen'),
(35, 'Unterscheide bitte geschlossene und offene Fragen in der Kundenkommunikation', 'Geschlossene Fragen: Ja-oder-Nein Fragen, Offene Fragen: W-Fragen - Wer, Wie, Was, Wieso, Warum, Wann', 'Informieren und Beraten von Kunden und Kundinnen'),
(36, 'Das Controlling im Unternehmen wird als eine Funktion des Managements gesehen, dessen zentrale Aufgabe die Planung, Steuerung sowie die Kontrolle aller Unternehmensbereiche ist. Wozu dient dabei eine ABC-Analyse?', 'Die ABC-Analyse dient dazu, Dinge nach ihrer Wichtigkeit oder ihrem Wert zu sortieren. In einem Unternehmen hilft sie, herauszufinden, welche Bereiche oder Produkte den größten Einfluss auf den Erfolg haben. A-Gruppe: Sehr wichtige Dinge, die viel Einfluss haben (meist 10-20% der Dinge machen 70-80% des Erfolgs aus). B-Gruppe: Mittlere Wichtigkeit. C-Gruppe: Weniger wichtige Dinge, die wenig Einfluss haben.', 'Informieren und Beraten von Kunden und Kundinnen'),
(37, 'Was versteht man unter dem Begriff Cross-Selling?', 'wird das Bemühen eines Händlers bezeichnet, zusätzlich zu einem nachgefragten Artikel weitere passende Produkte oder Services anzubieten', 'Informieren und Beraten von Kunden und Kundinnen'),
(38, 'Ergänze nach dem Vier-Ohren-Modell (Sachebene, Appell, Selbstoffenbarung und Beziehung) die folgenden Aussagen: 1. Sie müssen pünktlich liefent! 2. ich bin mit Ihnen nicht zufrieden. 3. Sie haben nicht pünktlich geliefert. 4. Ich kontrolliere Ihre Leistungen sehr genau.', '1. Appell: Sie müssen pünktlich liefent! 2. Beziehung: ich bin mit Ihnen nicht zufrieden. 3. Sachebene Sie haben nicht pünktlich geliefert. 4. Selbstoffenbarung: Ich kontrolliere Ihre Leistungen sehr genau.', 'Informieren und Beraten von Kunden und Kundinnen'),
(39, 'Welche Regeln sollte man im telefonischen Kundensupport beachten?', '- Vermeide Ausdrücke, die den Kunden reizen könnten - Höre dem Gesprächpartner aktiv zu - Lass Kunden immer ausreden und unterbricht sie nicht - widersprich nicht bei einer Beschwerde - Hinterfrage mit W-Fragen (wann, wie, wo)', 'Informieren und Beraten von Kunden und Kundinnen'),
(40, 'Beschreibe den Begriff Pre-Sales-Angebot und nenne 3 Beispiele.', 'Pre-Sales-Angebot ist ein Angebot, das ein Unternehmen vor dem tatsächlichen Verkauf an einen Kunden erstellt. Es dient dazu, dem Kunden zu zeigen, was er von einem Produkt oder einer Dienstleistung erwarten kann, und ihn davon zu überzeugen, einen Kauf zu tätigen. Beispiele: Testversion eines Produkts, Kostenlose Probefahrt beim Fahrzeugverkauf, Kostenlose Beratung', 'Informieren und Beraten von Kunden und Kundinnen'),
(41, 'Welche Vor-und Nachteile bieten Webinare?', 'Vorteile: keine Reisekosten, Webinare können aufgezeichnet werden für Wiederholungen, Kurse sind individuell kurzfristig planbar, eine Vielzahl an Teilnehmern ist erreichbar. Nachteile: Umsetzung von Praxisbezogene Übung nicht immer möglisch, setzt eine funktionierende technische Ausstattung ind Internetverbindung voraus, keine gemeinsamen Aktivitten der Teilnehmer.', 'Informieren und Beraten von Kunden und Kundinnen'),
(42, 'Nenne die Englischen Bezeichnungen der einzelnen Schichten im OSI-Referenzmodell.', '1. Physical Layer 2. Data Link Layer 3. Network Layer 4. Transport Layer 5. Session Layer 6. Presentation Layer 7. Application Layer', 'Informieren und Beraten von Kunden und Kundinnen'),
(43, 'Was ist eine Nutzwertanalyse?', 'ist ein Verfahren, mit dem man verschiedene Optionen oder Alternativen miteinander vergleicht, um die beste Lösung für ein bestimmtes Ziel zu finden. Dabei werden verschiedene Kriterien bewertet und gewichtet. Es hilft, Entscheidungen zu treffen, indem man die Vor- und Nachteile jeder Option systematisch abwägt.', 'Informieren und Beraten von Kunden und Kundinnen'),
(44, 'Unternehmen müssen Ihre Produkte am Markt anbieten. dazu benötigen sie einen Vertriebspartner oder ein Vertriebnetz. Nenne Vor-und Nachteile eines direkten Vertriebs.', 'Vorteile: die Gewinnspanne ist höher, Endverbraucher haben kurze Kommunikations-und Vertriebswege, engere Kundenbindung durch persönliche Kundenkommunikation. Nachteile:eigenes Vertriebsnetz bindet viel Kapital, hohe fixkosten, Massendistribution nur bedingt umsetzbar.', 'Informieren und Beraten von Kunden und Kundinnen'),
(45, 'Mit welchen Maßnamen kann man die Kundenzufriedenheit erhöhen?', 'Folgende Massnahmen sind geeignet: Rabbat Gewährung, Teilname an Sonderaktionen, Einladung zu Hausmessen oder Festen, Feedback einholen durch Umfragen, Social Media, Einrichtung von Bewertungsportal', 'Informieren und Beraten von Kunden und Kundinnen'),
(46, 'Welchem Zweck dient ein Angebotsvergleich?', 'Ein Angebotsvergleich dient dazu, verschiedene Angebote zu vergleichen, um die beste Lösung in Bezug auf Preis, Qualität und Leistung zu finden. Ziel ist es, eine informierte Entscheidung zu treffen und das beste Angebot für die eigenen Bedürfnisse auszuwählen.', 'Informieren und Beraten von Kunden und Kundinnen'),
(47, 'Was ist bei der Außerbetriebnahme von IT-Systemen zu beachten?', 'Daten sichern: Alle wichtigen Daten müssen gesichert und ggf. auf ein anderes System übertragen werden. Daten löschen: Vertrauliche oder sensible Daten müssen vollständig gelöscht werden, um Missbrauch zu verhindern. Hardware entsorgen: Die Hardware muss umweltgerecht entsorgt oder wiederverwendet werden. Lizenzen und Verträge prüfen: Lizenzvereinbarungen und Verträge sollten überprüft und gegebenenfalls gekündigt werden', 'Informieren und Beraten von Kunden und Kundinnen'),
(48, 'Worin besteht in der Virtualisierung von Hostsystemen der Unterschied zwischen dem Hypervisor Typ 1 und Typ 2?', 'Typ 1 (Bare-Metal) ist direkter und schneller Der Hypervisor läuft direkt auf der Hardware des Hosts, ohne ein Betriebssystem dazwischen.  Typ 2 (Hosted)  ist weniger effizient, da er ein Betriebssystem benötigt, um zu arbeiten.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(49, 'Welche Fuktionen bietet eine Dockingstation für Notebooks?', 'Erweiterung der Anschlüsse, Einfache Verbindung, Laden des Notebooks. Die moderne Dockingstationen verfügen über die möglichkeit 2x HDMI, 2x DVI oder 2x Displayport zu nutzen.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(50, 'Welche Video-Schnittstellen sind für 4K und 8K Auflösungen geeignet?', 'HDMI 2.0 max. Auflösung 4K, HDMI 2.1 max. Auflösung 8K, DisplayPort 1.3 und 1.4 max. Auflösung 8K', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(51, ' Welche technischen Merkmale hat ein Notebook?', 'teilweise Anschluss für Dockingstation, eigenes Display, integrierte Lautsprecher und Mikrofone, Interne Netzwerkkarte, externes Netzteil, teilweise Videokamera', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(53, 'Welchen Vorteil bringt der Einsatz von Dual-Channel-Technik bei Speichermodulen?', 'Es sorgt dafür, dass dein Computer schneller auf den Speicher zugreifen kann Dabei werden zwei Speichermodule gleichzeitig genutzt, was die Datenübertragungsrate verdoppelt und somit die Leistung des Systems verbessert. ', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(54, 'was verbirgt sich hinter Bezeichnung UHD 4K?', 'UHD 4K bezeichnet ein digitales Videoformat (4096x2160 Pixel) die Hersteller spezifizieren jedoch ihre Geräte mit 3840x2160 Pixeln', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(55, 'Was versteht man unter einem Thin-Client?', 'Ein Thin Client ist ein einfaches Computergerät, das sich hauptsächlich auf einen zentralen Server verlässt, um Programme auszuführen und Daten zu speichern. Es hat wenig eigene Rechenleistung und Speicher, da die meisten Aufgaben vom Server übernommen werden.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(56, 'Welche IT-Lomponenten sind Ein-oder Ausgabegeräte? a) Drucker b)Scanner c)Maus d) Display e)Touchpad', 'Eingabegeräte: b) scanner c) Maus e) Touchpad  Ausgabe: a) Drucker d) Display', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(57, 'Nennen die Verschiedenen Cloud-Formen, die durch Cloud Computing angeboten werden', 'Public Cloud:  stellt zugang für die Öffentlichkeit über das Internet bereit Private Cloud: stellt für eine Organisation den zugang in eine Cloud-Umgebung bereit Hybrid: ist eine Kombination aus Public und Privat', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(58, 'Was versteht man unter dem Begriff Green-IT?', 'Green-IT bezeichnet umweltfreundliche und energieeffiziente Technologien in der IT, um Ressourcen zu schonen und den Energieverbrauch zu reduzieren.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(59, 'Erkläre den Begriff des Servicemodells infrastructure as a Service (IaaS)', 'Infrastructure as a Service (IaaS) ist ein Cloud-Servicemodell, bei dem Unternehmen IT-Ressourcen wie Server, Speicher und Netzwerke über das Internet mieten. Statt eigene Hardware zu kaufen, nutzen sie flexible, skalierbare Infrastruktur von Anbietern wie AWS, Azure oder Google Cloud', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(60, 'Erkläre den Cloud Computing Begriff Software as a Service (SaaS)', 'SaaS bedeutet, dass Software über das Internet genutzt wird, anstatt sie lokal zu installieren. Anbieter hosten und verwalten die Anwendungen, einschließlich Updates und Sicherheit. Nutzer greifen einfach per Browser darauf zu. Beispiele: Google Drive, Microsoft 365, Dropbox.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(61, 'Was ist ein Host-Bus-Adapter?', 'Ein Host-Bus-Adapter (HBA) ist eine Hardwarekomponente, die einen Computer mit einem Speichersystem verbindet. Er ermöglicht die Kommunikation zwischen dem Rechner und Speichergeräten wie SCSI-, Fibre-Channel- oder SATA- bzw. SAS-Festplatten. HBA verbessert die Datenübertragungsrate und entlastet die CPU.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(62, ' Nenne Die Vorteile des Servicemodells Paas (Platform as a Service)', '-  mit dem Paas-Entwicklungstools reduziert sich der Zeitaufwand für das Schreiben von Code für neue Apps. - Entwicklungsteam können neue Funktionen mit Hilfe der Paas- Komponenten nutzen, ohne diese selbst Entwickeln zu müssen. - Kostengünstige Nutzung von Tools. - Effiziente Verwaltung des Anwendungslebenszyklus.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(63, 'Eine unterbrechungsfreie Stromversorgung (USV) wird nach der USV-Klassifizierung in 3 Klassen unterteilt. Nenne die 3 Klassen und erkläre deren Wirkungsweise stichpunktartig.', 'Klasse 1:VFI (Voltage and Frequency independent from main supply) Schützt vor den Folgen eines Stromausfalls, Unterspannung,Überspannung als auch Frequencschwankungen und Oberschingungen. Klasse 2:VI (Voltage Independent from mains supply) Schützt vor den Folgen eines Stromausfalls, vor Unterspannung und vor Überspannung. Klass 3:VFD (Voltage and Frequency Dependent on mains supply) Schützt vor den Folgen eines Stromausfalls, jedoch mit einer Verzögerung von bis zu 10 Millisekunden(ms)', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(64, 'IT-Infrastruckturen werden 24/7 betrieben. Welche Aufgaben übernimmt in diesem Zusammenhang eine USV?', 'eine USV  soll die Elektrische Versorgung der systemrelevanten IT-Komponenten 24/7 sicherstellen sowie Störungen im Stromnetz zeitlich überbrücken.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(65, 'Welche Aufgabe übernimmt ein Datenbankmanagementsystem, kurz DBMS', 'DBMS übernimmt Aufgaben: -Speicherung, Veränderung und Löschung von Daten, - Verwaltung der Metadaten. - Gewährleistung der Datensicherheit und des Datenschutzes. - Unterstützt die Optimierung von Abfragen. - trifft vorkehrungen zur Datenintegrität.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(66, 'Beschreiben Sie vor - und Nachteile des Laufwerksverbuns Just a Bunch of Disks(JBOD)', 'Vorteile: - Preiswerte alternative zur Erweiterung der Speicherkapazität, - Nutzt zu 100% die Kapazität aller Laufwerke aus, - ist leicht zu implementieren. Nachteile: - Durch Hardwareausfall können Daten verloren gehen, - Beim JBOD fehlt die Redundanz (kein echtes Raidsystem) - Bietet keine Geschwindigkeitsvorteile gegenüber echten RAID-Systemen, wie RAID 5', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(67, 'Was ist DMZ', 'Demilitarisierte Zone trennt durch Subnetz mit Hilfe von Firewall-Routern das interne Netzwerk vom externen Netzwerken ab. In der Firewall üner die sogenannten Firewall-Regeln wird geregelt welche Datenpakete in welche Richtung das Subnetz passieren dürfen', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(68, 'Welche Aufgabe hat ein Netzwerk-Router?', 'Router ist ein Netzwerkgerät, welches sich im OSI-Model auf der Schicht 3 befindet und die Netzwerkpakete zwischen mehreren Netzwerken weiterleitet.Netzwerkrouter werden zur sicheren Kopplung mehrerer Standartorte über VPN oder zur direkten Verbindung mehrerer lokaler Netzwerksegmente eingesetz. Router sind in der Lage unterschiedliche Netzwerktechniken, wie Ethernet, DSL, PPPoe usw. miteinander zu verbinden', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(69, 'Nenne die 4 transportorientierten Schichten des OSI-Modells und erläutere deren Aufgabe', 'Schicht 1 -Bitübertragungsschicht stellt die Physischen Verbindung her um die Datenbits zu übertragen (HUB, Netzwerkkabel) Schicht 2 - Sicherungsschicht gewährleistet eine zuferlässige und fehlerfreie übertragung und den Zugriff auf das Übertragungsmedium (Switch, Acces Point, Bridge) Schicht 3 - Vermittlungsschicht das Bereitstellen von Netzwerk-übergreifenden Adressen (IPv4/IPv6), das Routing, sowohl Aufbau als auch die Aktualisierung von Routingtabellen. Schicht 4 - Transportschicht zuständig für fehlerfreie Übertragung sowie für Datensegmintierung und für die Datenkapselung durch protokollelemente verantwortlich. ', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(70, 'Was ist Broadcast-Domäne?', 'Eine Broadcast-Domäne ist ein Netzwerkbereich, in dem ein Broadcast-Paket von allen Geräten empfangen wird. Ein Broadcast ist eine Nachricht, die an alle Geräte innerhalb eines Netzwerks gesendet wird, indem sie an die MAC-Adresse FF:FF:FF:FF:FF:FF gerichtet wird.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(71, 'Was ist ein NAS?', 'NAS ist ein eigenständiges Speichersystem, das über das Netzwerk verbunden ist und Datei-basierten Zugriff ermöglicht. wird für einen einfach zu verwaltenden Dateiserver benutzt. Nutzt Netzwerkprotokolle wie NFS, SMB/CIFS oder FTP.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(72, 'Was ist ein Storage Area Network (SAN)?', 'SAN ist ein Hochleistungs-Speichernetzwerk, das Block-basierten Zugriff ermöglichtund nutzt Speicherprotokolle wie Fibre Channel (FC), iSCSI oder FCoE. Typische Verwendung: Große Unternehmen, Datenbanken, Virtualisierung, Hochleistungsanwendungen. ', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(73, 'Das Unternehmennetzwerk (192.168.30.0/24) soll in 8 Subnetze unterteilt werden. wie lautet die korrekte Subnetzmaske und wie viele Hosts IP-Adressen kann ich zusammen in allen 8 Subnetzen nutzen? ', '8 Subnetze = 2³ Subnetzmaske: 255.255.255.224 oder /27 Hosts: 240 (8*32 (Minus Netz-ID und Broadcastsadresse) 0 8*30 =240)', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(74, 'Was bedeutet der Begriff PoE?', 'PoE (Power over Ethernet) ist eine Technologie, die sowohl Daten als auch Strom über ein einziges Ethernet-Kabel überträgt. Typische Verbraucher: -IP-Telefonie - IP-Kameras - Smart Home / IoT ', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(75, 'Wie lautet die Notation einer iSCSI-Verbindung?', 'ist ein Protokoll, das SCSI-Befehle über ein IP-Netzwerk überträgt, um Speichergeräte wie SANs anzubinden. Eine iSCSI-Verbindung wird durch eine eindeutige Kennung identifiziert, die meist in der IQN-Notation (iSCSI Qualified Name) vorliegt. (iqn.yyyy-mm.reverse-domain:unique-name) Beispiel: iqn.2024-03.com.example:storage.target1  ', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(76, 'Wie wird eine Fibre Channel verbindung adressiert', 'Fibre Channel (FC) ist ein Hochgeschwindigkeits-Netzwerkprotokoll für Storage Area Networks (SANs). Geräte in einem FC-Netzwerk werden über WWN (World Wide Name) adressiert, ähnlich wie MAC-Adressen in Ethernet-Netzwerken.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(77, 'Erläutere den Begriff Unicast aus dem Bereich der Netzwerkkommunikation.', 'Unicast wird verwendet, wenn eine direkte Punkt-zu-Punkt verbindung zwischen Sender und Empfänger hergestellt werden soll. Der Sender kommuniziert gezielt nur mit einer  IP-Adresse des Empfängers im Netzwerk.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(78, 'Was versteht man unter dem Begriff Multicast?', ' Wenn der Sender zu einer definierten Empfängergruppe zeitgleich Daten überträgt, spricht man von Multicast. Wie viele Empfänger die Daten empfangen ist dabei irrelevant', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(79, 'Erläute bitte den Begriff Broadcast', 'im Broadcast Datenpakete werden vom Sender ungefragt an alle Empfänger gesendet', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(80, 'Welche Aufgabe hat bei IPv4 eine Broadcast-Adresse?', 'Mit Hilfe einer Broadcast-Adresse werden alle Netzwerkgeräte eines lokalen Netzwerkes erreicht, ohne es dediziert anzugeben. Broadcasts sind immer auf das eigene lokale Netzwerk beschränkt und werden nicht über Router weitergeleitet. sie ist immer die letzte IP-Adresse des Subnetzes.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(81, 'Beschreibe die Bestandteile einer IPv6-Adresse', 'eine IPv6-Adresse ist binär 128 Bit lang und besteht aus zwei Teilen, dem Netzwerk Präfix und dem Netzwerk Schnittstelle. Jeder teil ist binär 64 Bit lang und wird hexadezimal in jeweils 16 Bit Länge, durch Doppelpunkte getrennt dargestellt.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(82, 'Kürze die Schreibweise der IPv6 Adresse 2003:00dc:075a:dd00:e130:c353:3188:afb6 ein und definiere den 64-Bit Interface-Anteil (Netzwerk Schnittstelle)', '2003:dc:75a:dd00:e130:c353:3188:afb6. Interface-Anteil: e130:c353:3188:afb6', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(83, 'Bennene die IPv6-Adressbereiche -::1/128, -fe80::/10, -2000::/3, -ff00::/8', '::1/128 - Loopback, -fe80::/10 - Link-Local Address, 2000::/3 - Global Unicast, -ff00::/8 - Multicast', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(84, 'Was versteht man unter einer Stateless Adress Autokonfiguration? (SLAAC)', 'SLAAC in IPv6 ist das Äquivalent zum APIPA bei IPv4. stateless bekommt jedes IPv6-Stack per Autokonfiguration eine link-lokale IPV6 zugewiesen. die link-lokale Adresse beginnt immer mit FE80:.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(85, 'Worin unterscheiden sich die Lichtwellenleiter der Single- und Multimodefassern?', 'Singlemode-Fasern haben einen sehr dünnen Kern (9 µm) und transportieren das Licht in nur einem geraden Strahl. Dadurch gibt es kaum Signalverluste, und die Daten können über sehr lange Strecken (bis zu 100 km) übertragen werden. Sie werden für Telekommunikation und Weitverkehrsnetze genutzt, sind aber teurer. Multimode-Fasern haben einen dickeren Kern (50 µm oder 62,5 µm) und lassen das Licht in mehreren Strahlen gleichzeitig reflektieren. Dadurch entstehen mehr Verluste, und die Reichweite ist begrenzt (max. 550 m). Sie sind günstiger und werden meist in Rechenzentren oder Bürogebäuden genutzt. ', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(86, 'Nenne Vor-und Nachteile von Singlemode-Glasfasern', 'Vorteile: geringe Dämpfung des Signals, Große Distanzen überbrückbar, hohe Bandbreiten Nachteile: größerer Aufwand bei der Herstellung der Glasfassern aufgrund der sehr kleinen Fasekerne, teuere Laser zur Einspeisung des Lichts notwendig', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(87, 'Nenne Vor-und Nachteile von Multimodefassern.', 'Vorteile: geringere Aufwand in der Herstellung der Glasfasern, einfache Verbindungstechnik aufgrund des größeren Kerndurchmessers Fasern mit Stufenindex und Gradientenindexprofil verfügbar Nachteile: größere Signaldämpfung und Laufzeitverschiebung, geringere maximale Bandbreite, nur kürze Distanzen überbrückbar', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(88, 'Welche Aufgabe hat das Simple Network Management Protocol (SNMP)?', 'SNMP ist ein Netzwerkprotocol mit dem Ziel, Netzwerkelemente wie Router, Server, Switches , Drucker, Computer und andere SNMP-tauglische Geräte mit hilfe einer zentralen Management Konsole aus aus überwachen und steuern zu können', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(89, 'Welche Aufgaben hat ein DHCP-Server innerhalb der IT-Infrastruktur?', ' vergibt automatisch IP-Adressen und Netzwerkkonfigurationen an Geräte im Netzwerk. Dadurch müssen IP-Adressen nicht manuell eingestellt werden, was die Verwaltung erleichtert.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(90, 'Was versteht man im Netzwerkbereich unter dem Quality of Service?', 'Quality of Service (QoS) bezeichnet Mechanismen im Netzwerk, die den Datenverkehr priorisieren, um eine stabile und zuverlässige Übertragung sicherzustellen. Das wird durch verschiedene Techniken erreicht: Priorisierung von Datenpaketen nach Anwendung oder Gerät, Bandbreitenmanagement, um Engpässe zu vermeiden, Minimierung von Verzögerungen (Latenz) und Datenverlust. QoS wird oft in Unternehmen, Cloud-Diensten oder bei Echtzeitkommunikation eingesetzt, um eine gleichbleibende Netzwerkkapazität zu gewährleisten.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(91, 'Wann kommt ein tagged VLAN zum Einsatz?', 'Ein tagged VLAN wird eingesetzt, wenn mehrere VLANs über eine einzige Netzwerkverbindung (Trunk) transportiert werden sollen. Dabei werden die Datenpakete mit einer VLAN-ID (Tag) versehen, damit die Switches erkennen, zu welchem VLAN sie gehören.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(92, 'Beschreibe typische Merkmale des Clients-Server-Modells.', 'Client-Server-Konzept beschreibt ein Prinzip, Aufgaben und Services innerhalb eines bestimmten NEtzwerkes zu verteilen. Merkmale: Server stellen Dienste bereit, ein Server bedient ein oder mehrere Clients, Clients fragen Dienste bei Server an ', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(93, 'Welche Aufgaben hat ein Domain Name System (DNS) in einer Windows Domänenlandschaft bzw. Active Directory?', 'DNS dient der Beantwortung von Anfragen zur Namenauflösung. In Windowsbasierten Domänen kommt zusätzlich der Reverse Lookup Anfrage die Aufgabe zu. Dieses Revorse Lookup wird mit Hilfe von PTR Ressource Records in der Reverse Lookup Zone des Active Directory gewährleistet. ', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(94, 'E-Mail-Dienste: Unterscheide die Mailingprotokolle IMAP/S, SMTP/S sowie POP3/S nach ihren Eigenschaften', ' IMAP/S (Internet Message Access Protocol / Secure) wird hauptsächlich für den Zugriff auf E-Mails auf einem Mailserver verwendet. Es ermöglicht es den Nutzern, ihre E-Mails auf dem Server zu verwalten, anstatt sie lokal herunterzuladen. läuft standardmäßig auf Port 993. SMTP/S (Simple Mail Transfer Protocol / Secure) ist verantwortlich für den Versand von E-Mails, jedoch nicht für das Empfangen von Nachrichten. sichere Variante SMTPS läuft über Port 465. POP3/S (Post Office Protocol 3 / Secure) wird verwendet, um E-Mails vom Mailserver herunterzuladen und auf dem lokalen Gerät zu speichern. Im Gegensatz zu IMAP werden E-Mails bei POP3 in der Regel vom Server gelöscht, nachdem sie heruntergeladen wurden. Es läuft normalerweise über Port 995.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(95, 'Switch arbeitet auf Schicht 2, Verarbeitet Ethernet Frames nach IEE 802.3, arbeitet MAC-Adressenbasiert. Router: arbeitet auf Schicht 3, routet Netzwerke, verarbeitet Protokolle wie OSPF, RIP, IS-IS', '', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(96, 'Was bedeutet der Begriff Standby- oder Offline USV?', 'Die einfache unterbrechungsfreien Stromversorgungen der USV-Klasse 3 sind Offline-USVs. Sie schützen generel nur gegen Stromausfälle sowie kurzzeitige Spannungsschwankungen. Umschaltdauer von 4 bis 10 ms. ', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(97, 'Was versteht man unter einer Online-USV?', 'Die online-USV (USV-Klasse 1) gilt als die teuerste Variante bietet auch den umfassendsten Schutz durch permanente erzeugung einer Sinusspannung am Ausgang. Alle angeschlossenen Verbraucher werden dauerhaft und ohne Einschränkungen mit Netzspannung versorgt, während zeitgleich die Batterie aufgeladen wird. Bei Netzausfall erfolgt ein unterbrechungsfreier Übergang auf die Batterieeinspeisung', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(98, 'was versteht man unter der Bezeichnung Netzinteraktive USV?', 'Netzinteraktive USV (USV-Klasse 2) funktioniert ähnlich wie das Offline- USV. Nur im gegensatz zur Offline-USV liegen die Umschaltzeiten vom Netzbetrieb zum Batteriebetrieb zwischen kurzen 2 bis 4 ms. Die Umschaltzeit vom Batteriebetrieb zum Netzbetrieb ist nahezu verzögerungsfrei.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(99, 'Was bedeutet der Begriff SSID?', 'Service Set Identifier ist freiwählbare Name eines dratlosen Netzwerkes wird oft als Netzwerkname bezeichnet.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(100, 'Was versteht man unter den Begriffen CMS-,ERP-und CRM-System?', 'Content Management System ist eine Software, die es ermöglicht, digitale Inhalte zu erstellen, zu verwalten und zu bearbeiten, insbesondere für Websites. Ein Enterprise Resource Planning ist eine integrierte Softwarelösung, die verschiedene Geschäftsprozesse innerhalb eines Unternehmens verwaltet und optimiert. Customer Relationship Management (CRM)-System ist eine Software, die Unternehmen dabei hilft, die Interaktionen mit ihren Kunden zu verwalten und zu analysieren.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(101, 'Welche Maßnamen sind geeignet, um die Verarbeitungsgeschwindigkeit eines Personal Computers zu verbessern?', '- Austausch von SATA HDDs mit geringer Umdrehungszahl gegen HDDs mit 10K/rpm - Einsatz von SSD/M.2 gegenüber Sata-HDDs - Aufteilung des Betriebssystem und der Anwendungsprogramme auf unterschiedlichen Datenträgern - Austausch 100Mbit/s Netzwerkkarte gegen 1 Gbit/s Netzwerkkarte', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(102, 'Ermittle Vor-und Nachteile einer M.2-SSD.', 'Vorteile: Lesegeschwindigkeiten von bis zu 7.450 MB/s, kleines kompaktes Design welches, keinen zusätzlichen Platz benötigt, Keine Verkabelung notwendig, wird direkt auf das Motherboard gesteckt, NVMe Unterschtützung. Nachteile: Teuer als herkömmliche SATA-SSds, noch nicht alle Motherboards unterstützen M.2-SSDs, Warmeentwicklung: bei intensiver Nutzung wird heiß, Speicherkapazität: bietet nicht die gleichen Kapazität wie herkömmliche SATA-SSds an', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(103, 'Erläutere den Begriff des CPU-Caches', 'ist ein zusätzlicher Speicher auf dem Prozessor. mit ihm sollen die Zugriffszeiten verkürzt werden. man bezeichnet diesen CPU-Cache aus als eine Art Zwieschenspeicher, der in Schnelligkeit und Größe variiren kann. man unterscheidet nach L1, L2 und L3-Cache. L1- ist der schnellste und auch kleinste Zwischenspeicher. L2 ist etwas langsame und größe und L3 ist der Größte und langsamste. Alle drei Cache-Level sollen den Arbeitsspeicher entlasten und CPU einen schnellen Zugriff auf Daten und Befehle ermöglichen.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(104, 'Wie berechnet man die Wirkleistung von elektrischen Geräten?', 'die elektrische Wirkleistung P ist das Produkt von Spannung und der Stromstärke I. die Berechnung erfolgt wie folgt: P = U * I = VA/W. ', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(105, 'Was bedeutet es, wenn ein WLAN Acces Point im Infrastructure Modus arbeitet?', 'das bedeutet, dass Clients über den WLAN Acces Point ein weiteres Netzwerk erreichen können, wie z.B das Unternehmensnetzwerk. Clients müssen sich dazu mit Hilfe ihrer Zugangsdaten und MAC-Adresse anmelden. für die Anmeldung gibt es verschiedene Möglichkeiten wie WPA2, WPA3, RADIUS und WPS.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(106, 'Was bedeutet es, wenn ein WLAN Acces Point im Infrastructure Modus arbeitet?', 'das bedeutet, dass Clients über den WLAN Acces Point ein weiteres Netzwerk erreichen können, wie z.B das Unternehmensnetzwerk. Clients müssen sich dazu mit Hilfe ihrer Zugangsdaten und MAC-Adresse anmelden. für die Anmeldung gibt es verschiedene Möglichkeiten wie WPA2, WPA3, RADIUS und WPS.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(107, 'was bedeutet der Begriff MIMO im Bereich der Nachrichtentechnik?', 'Multiple Input Multiple Output ist  die gleichzeitige Nutzung mehrerer Antennen sowohl auf der Sender- als auch auf der Empfängerseite beschreibt. wird in vielen modernen Kommunikationssystemen eingesetzt , wie z.B in Wi-Fi und Mobilfunknetzen (z.B 4G und 5G). Es ermöglicht, die verfügbaren Frequenzen effizienter zu nutzen und so die Leistung des Netzwerks zu steigern.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(108, 'was bedeutet der Begriff MIMO im Bereich der Nachrichtentechnik?', 'Multiple Input Multiple Output ist  die gleichzeitige Nutzung mehrerer Antennen sowohl auf der Sender- als auch auf der Empfängerseite beschreibt. wird in vielen modernen Kommunikationssystemen eingesetzt , wie z.B in Wi-Fi und Mobilfunknetzen (z.B 4G und 5G). Es ermöglicht, die verfügbaren Frequenzen effizienter zu nutzen und so die Leistung des Netzwerks zu steigern.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(109, 'Was versteht man unter dem Begriff Multi SSID?', 'Mit Hilfe von WLAN Acces Point, die das Feature Multi-SSID  anbieten, ist es möglich, mehrere virtuelle voneinander getrennte WLAN Bereiche anzubieten. Die WLAN Bereihe sind in der Regel durch verschiedene Netzwerksegmente und Zugangsmöglichkeiten voneinander getrennt.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(110, 'Nenne Vor-und Nachteile beim Einsatz eines 2.4 GHz sowie eines 5 GHz Wireless Local Area Networks.', '2.4: Vorteil : Das 2.4 GHz-Band bietet eine größere Reichweite und eine bessere Durchdringung von Wänden und Hindernissen, Weitverbreiteter Funkstandart, besser geeignet, größere Entfernungen zu überbrücken. Nachteile: Das 2.4 GHz-Band hat nur 3 nicht überlappende Kanäle (1, 6, 11), was bei vielen Geräten und Netzwerken zu Störungen führen kann,  Die maximale Datenrate ist niedriger als bei 5 GHz. 5 GHz: Vorteile : höhere Datenraten und eine bessere Performance, ideal für HD-Streaming, Online-Gaming, weniger überlastet ist als das 2.4 GHz-Band, höhere Geschwindigkeit. Nachteile: Das 5 GHz-Band hat eine kürzere Reichweite und kann Wände und Hindernisse nicht so gut durchdringen wie das 2.4 GHz-Band, Kurze Reichweite: 5 GHz-Signale breiten sich in der Regel weniger weit aus, sodass der Empfang in entlegenen Bereichen oder Etagen eingeschränkt sein kann.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(111, 'Welche Technischen Spezifikationen hat Bluetooth in Bezug auf Reichweite, Datentransferrate und Frequenzbereich?', 'die Reichweite wird in Klassen unterschieden: Klasse 1: max.sendeleistung:100mW/20dBm reichweite: 200m Klasse 2: max Sendeleistung 2,5mW/4dBm reichweite: 20m Klasse 3: 1mW/0 dBm reichweite: 10m. Datatransfer: Basic Rate - 1MBit/s. Enhanced Data Rate - 2-3 MBit/s', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(112, 'Nenne die Vor-und Nachteile der Virtualisierung von Servern und Desktops auch unter Berücksichtigung von Cloudangeboten.', 'Vorteile: Stromsparnis, Skalierbarkeit, Ausfallsicherheit, so gut wie keine Kapazitätsbeschrenkungen, keine Investitionskosten bei Cloudanbieter. NAchteile: eventuell höhere Latenzzeiten mit vielen virtuallen Machienen pro Host, Hardware und Software kann nicht zu 100% selbst administriert werden, nicht jede Lösung ist kostengünstig 24/7-Einsatz', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(113, 'Was bedeutet der Begriff Serverkonsolidierung?', 'Serverkonsolidierung bedeutet, mehrere Server auf weniger physische Maschinen zu reduzieren. Das passiert oft durch Virtualisierung, bei der mehrere virtuelle Server auf einem leistungsstarken physischen Server laufen. Das spart Kosten, Platz und Energie und vereinfacht die Verwaltung.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(114, 'Welche Arten von Anforderungen gibt es an Software?', 'Geschäftsanforderungen, welche sich aus der Geschäftstätigkeiten des Kunden und den Marktanforderungen ergeben. Benutzeranforderungen, Funktionale Anforderungen - erfassen das Verhalten, welches eine Software erfüllen muss, um die Benutzeranforderungen zu gewährleisten, Projektanforderungen, die den Erfolg eines Projekts sichern.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(115, 'Welche Kosten entstehen für ein Rechenzentrum (on-Premises) mit einer Server-Client Struktur?', '- Kauf, Miete für Gebäude/Raum - Anschaffungskosten(Hardware, Software, Kuühlung) - Lizensgebühren(Betriebsystem/Anwendersoftware) - Wartung - Versicherungen - Brandschutz - Energiekosten ...', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(116, 'Was versteht man unter dem Begriff der Bedarfsanalyse?', 'eine Analyseart zur Feststellung des Bedarfs an Waren, Dienstleistungen, Gütern oder Personal. Der Zweck der Bedarfsanalyse besteht darin, zukünftige Beschaffungsprozesse oder Projekte besser zu planen.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(117, 'Nenne die Vortile einer Bedarfsanalyse.', '- dentifiziert genau, was benötigt wird und warum. Verhindert Missverständnisse und unnötige Ausgaben. -  Spart Zeit, Geld und Arbeitskraft, indem nur das Notwendige beschafft oder entwickelt wird. - Sorgt dafür, dass Kundenbedürfnisse im Mittelpunkt stehen.\r\n- Erhöht die Kundenzufriedenheit durch maßgeschneiderte Lösungen.', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(118, 'Vergleiche bitte BIOS mit UEFI.', 'UEFI: kann auch von Laufwerk mit 2,2 TB oder mehr booten. - grafische Benutzeroberfläche mit Mausbedienung. - unterschtützt 64-Bit-Prozessoren nativ ab Werk. - nutzt GPT-Partitionschema. BIOS: - keine Mausbedienung. - kann nur von Master-Boot-Record starten - kann nur von Laufwerken bis 2 TB booten', 'Beurteilen marktgängiger IT-Systeme und Lösungen'),
(119, 'Beschreibe die Funktionsweise einer Remote Desktop Verbindung. ', 'Eine Remote Desktop Verbindung stellt über das proprietäre Netzwerkprotokoll RDP von Microsoft einen Fernzugriff auf entfernte Computer her. Die Kommunikation im Netzwerk erfolgt über den TCP/UDP-Port 3389. Es werden grafische Bildschirminhalte sowie lokale Ressourcen eines Arbeitsplatzes wie Tastatur,Maus,Laufwerke, Drucker genutzt', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(120, 'Wie kann ich mit Hilfe von Kommandozeilen-Werkzeugen in einer windowsbasierten IT-Landschaft die Namensauflösung überprüfen? ', 'Eingabeaufforderung (CMD): -ping -a, -nslookup - tracert. PowerShell: -Resolve-DnsName', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(121, 'Nenne die 4 Features, die verhindern, dass während des Startvorgangs von Windows 10 Schadensoftware wie  Rootkits und Bootkits geladen werden können', '1. Sicherer Start (nur Vertrauenswürdige BetriebsystemStartladeprogramme geladen werden) 2. Vertrauenswürdiger Start (Windows überprüft während des Startvorgangs die Integrität jeder Komponente, bevor diese in den Arbeitsspeicher geladen wird ) 3. Early Launch Antimalware -mit dem ELAM werden alle Treiber vor dem Laden getestet, um zu verhindern, dass nicht zertifizierte oder genehmigte Treiber mit dem Betriebsystem geladen werden.)', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(122, 'Erläutere den Unterschied zwischen Partitionierung und Formatierung eines Datenträgers.', 'Die Partitionierung ist die physysche und logische Einteilung des Speichermediums in Volumes, welche Zusammenhängende sowie aufeinanderfolgende Datenblöcke logisch zusammenfasst. Die Formatierung: ist die logische Einteilung der Partitionsstruktur mit einem Dateisystem, wie z.B. NTFS oder Btrfs durch das Betriebsystem selbst oder durch eine entsprechende Software.', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(123, 'Was versteht man unter einem Service-Tag oder Asset-Tag?', ' Service-Tag oder Asset-Tag identifizieren Geräte mit einer eindeutigen Seriennummer oder einem Bar-oder QR-Code. es sind in der Regel Etiketten mit einer selbstklebenden Rückseite. Diese Tags werden zu Bestandskontrolle, Inventarisierung und zur Nachverfolgung der Hardware benutzt.', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(124, 'Welche Vorteile bringt der Einsatz von Thin-Clients in einer IT-Landschaft, die auf Desktop-Virtualisierung setzt', '- geringerer Stromverbrauch, -geräuschloser Arbeitsplatzcomputer, - geringer Platzbedarf am Arbeitsplatz, - leicht austauschbar, - geringes Gewicht, - flexibel einsetzbar, da kein Betriebsystem instaliert werden muss, - umweltfreundlich', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(125, 'Was versteht man unter einem Pflichtheft?', 'beschreibt wie der Auftragnehmer die Anforderungen des Auftraggebers umsetzen möchte. Man spricht hier über das sogenannte - Wie und Womit der Auftrag erfüllt werden soll. erst wenn der Auftraggeber den Pflichtenhelft akzeptiert, wird die Umsetzung begonnen ', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(126, 'was wird in einem Lastenheft beschrieben?', 'Ein Lastenheft beschreibt die Anforderungen eines Auftraggebers an ein Produkt, eine Software oder eine Dienstleistung. Es dient als Grundlage für die Entwicklung und Umsetzung eines Projekts.', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen');
INSERT INTO `karten` (`id`, `questen`, `answer`, `category`) VALUES
(127, 'Erläutere die Vor-und Nachteile beim Lizenzmodell Pay-per-use.', 'Vorteile: - man bindet keine finanziellen Mittel, - kann individuelle Leistungen skalieren, je nach Bedarf, - Unternehmen geht kein finanzielles Risiko ein. Nachteile: für den 24/7-Einsatz ist nicht immer kostengünstigste Variante, - Risiko bei Ausfall der Dienstleistung, da Service nicht selbst betrieben wird, - keine Spezialdienstleistungen möglich oder sehr teuer.', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(128, 'Was versteht man unter einem Convertible?', 'Ein Convertible Notebook (auch 2-in-1-Laptop genannt) ist ein Hybrid aus Laptop und Tablet. Es vereint die Funktionen eines klassischen Notebooks mit der Flexibilität eines Tablets. Merkmale: Klapp- oder drehbares Display, Touchscreen.  Verschiedene Betriebsmodi: Tablett Modus, Laptop Modus', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(129, 'Nenne einige Vor-und Nachteile von Tablets', ' Vorteile: -lange Akkulaufzeit, - Touchbedienung oder mit Stift, - platzsparend, - WLAN verbindung. Nachteile: -Schreiben auf der virtuallen Tastatur mit der Zeit anstrengend, - geringere Speicherkapazität gegenüber Notebooks, wenige Anschluss und Verbindungsmöglichkeiten.', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(130, 'Welche Vor-und Nachteile hat ein Notebook?', 'Vorteile: netzunabhängiges Arbeiten duch Akku möglich, - Netzzugriff mithilfe von WLAN Modulen, - integrierte Tastatur, Touchpad, - geringere Stromverbrauch als Desktop-PCs, ducrh dockingstation erweiterbar Nachteile: - geringe Festplattenspeicherkapazitäten, - Display oft kleiner als beim Desktop-Gerät, - technische Aufrüstung ist oft umständlich oder gar nicht möglich.', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(131, 'Welche Hard-und Softwareanforderungen werden an einen Dateiserver im Unternehmen gestellt?', 'redundantes Netzteil, redundanter Netzwerkzugriff, redundantes Plattensystem (RAID-Verbund) - Absicherung des Dateibestands durch Beckup oder Snapshots, Möglichkeit des Fernzugrifs via WebDAV oder (S)FTP', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(132, 'Worauf sollte man bei der Beschafuung von IT-Hardware achten?', ' Die folgenden Kriterien sind bei der Beschaffung von Hardware zu beachten: - kostengünstiger Support, - umweltfreundliches Produkt, leicht Austauschbar, schnelle Ersatzbeschaffung, - geringer Stromverbrauch und geringe Abwärme, - remote Management', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(133, 'Was versteht man unter Standartsoftware?', 'Als Standartsoftware bezeichnet man im Allgemein Software, die auf dem freien Markt angeboten wird. Im Gegensatz zur Individualsoftware ist sie vorgefertigt und muss in der Regel vom Anwender selbst installiert bzw.individuell angepasst werden. Standartsoftware Kann On-Premise und als Software as a Service angeboten werden. ', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(134, 'Was versteht man unter Individualsoftware?', 'Als Individualsoftware bezeichnet man Software, welche bestimmte Hardware-oder individuelle Geschäftsanforderungen erfüllen muss, also für einen bestimmten Anwender oder einen spezialisierten Verwendungszweck angefertigt wurde.', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(135, 'Was versteht man unter dem Begriff IDE?', 'IDE- Integrierte Entwicklungsumgebung ist eine Sammlung der wichtigsten Werkzeuge zu Softwareentwicklung unter einer einheitlichen Oberfläche. Sie soll helfen, die Arbeit des Anwendungsentwicklers zu erleichten. zu den Werkzeugen zählen z.B. Compiler, Debugger, interpreter. ', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(136, 'Was bedeutet der Begriff Proprietäre Software? ', 'Proprietäre Software ist Software, die jemandem gehört (z. B. einer Firma) und nicht frei verändert oder weitergegeben werden darf. Man braucht oft eine Lizenz, um sie zu benutzen, und der Quellcode ist meist nicht öffentlich. Beispiele sind Windows, Microsoft Office oder Adobe Photoshop.', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(137, 'Nenne 3 charakteristische Eigenschaften von Open Source Software. ', 'die 3 Merkmale: 1. Quelltext liegt in einer für den Menschen lesbaren und verständlichen Form vor. 2. Open Source Software darf beliebig kopiert, verarbeitet und genutzt werden. 3. Open Source Software darf verändert und in der veränderten Form weitergeleitet werden. ', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(138, 'Was ist unter den Begriffen OEM-Software und OEM-Hardware zu verstehen?', 'OEM(Original Equipment Manufacturer) wird vom Hersteller nicht direkt vertrieben. stattdessen wird diese an ein anderes Unternehmen ausgeliefert und z.B. in Verbindung mit weiteren Hardware/Software vertrieben. ', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(139, 'Was versteht man bei Rechenzentrumsbetrieb unter Skalierbarkeit? ', 'Unter der Skalierbarkeit versteht man die Fähigkeit einer Hardware oder Software, im laufenden Betrieb weiterhin zu funktionieren, wen Größe,Anzahl oder Volumen verändert wird. Diese Skalierbarkeit dient zjm Aufrechterhalten eines 24/7- Betriebs für die Kunden', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(140, 'Was beschreibt eine EULA(End User License Agreement) während des Installationsprozesses von Software', 'Sie enthält Regelungen, welche vei der allgemeinen Benutzung einer Software eingehalten werden sollen. EULA wird häufig zu Beginn des Instalationsprozesses angezeigt und ihr muss zugestimmt werden. andernfalls kann der Instalationsprozess nicht weitergeführt werden.', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(141, 'Beschreibe das Modell Pay-per-use in der Informationstechnologie.', 'Das Pay-per-Use-Modell bedeutet, dass man nur für die IT-Dienste bezahlt, die man tatsächlich nutzt. Statt eine Software oder Hardware komplett zu kaufen, zahlt man je nach Verbrauch, z. B. pro Stunde, pro Nutzer oder pro Datenmenge. Ein Beispiel ist Cloud-Speicher, wo man nur für den genutzten Speicherplatz bezahlt', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(142, 'Welche 3 VPN Verbindungsarten gibt es?', '1. End-to-Site-VPN, Site-to-Site-VPN, End-to-End-VPN', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(143, 'Mit welchen Maßnamen kann eine drahtlose Netzwerkverbindung( WLAN/WiFi) abgesichert werden?', 'Mit folgenden Maßnamen kann eine WLAN-Verbindung abgesichert werden: - Einsatz von Authentifizierungsmethoden wie WPA2/WPA3. - Einsatz eines RADIUS-Server. - Aktivierung von Mac-Filtern mit einer White List. - Einsatz eines Clients Zertifikats. - Nutzung von VPN-Verbindungen', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(144, 'Welche Merkmale hat ein Virtual Privat Network(VPN)', 'VPN ist ein logisches Netzwerk, welches eine geschützte Netzwerkverbindung unter Nutzung öffentlicher Netzwerke herstellt. mit Hilfe von Verschlüsselungstechnologien soll über eine VPN-Verbindung die Authentizität, die Vertraulichkeit und die Integrität der Daten sichergestellt werden. Um das zu gewährleisten gibt es verschiedene Protokollen und Lössungen wie L2TP over IPsec, OpenVPN und Layer-2-VPN. es gibt 3 Verbindungsarten (End-to-Site, Site-to-Site und End-to-End)', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(145, 'Beim Einsatz eines WLANs im Unternehmen welche Sicherheitsmethoden und Verschlüsselungsstandarts können zum Einsatz kommen?', 'Sicherheitsmethoden: -WOA(gilt als unsicher) -WPA2-Personal/Enterprise WPA3-Personal/Enterprise mit Radius. Verschlüsselungsstandarts: - Advanced Encryption Standart (AES) - Temporal Key Integrity Protocol (TKIP) - Simultaneous Authentication of Equals (SAE)', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(146, 'Welche Vorteile ergeben sich durch den Einsatz eines Virtual Local Area Networks(VLAN)', '- physikalische Netztopologie kann in logische Gruppen unterteilt werden. - Priorisierung des Datenverkehrs sind möglisch. - eine bessere Lastverteilung ist möglisch. - flexiblere Anpassung von Gruppenzugehörigkeiten. ', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(147, 'Welche Aufgabe erfüllt das Befehlzeilenkommando ARP?', 'Das ARP-Kommando (Address Resolution Protocol) zeigt die Zuordnung von IP-Adressen zu MAC-Adressen im lokalen Netzwerk an. Es hilft dabei, herauszufinden, welche MAC-Adresse (Hardware-Adresse) zu einer bestimmten IP-Adresse gehört.', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(148, 'Beschreibe die Aufgabe und Funktionsweise des Befehlszeilenkommandos chmod in einem Linux-Betriebssyste.', 'Der Befehl chmod in Linux wird verwendet, um die Zugriffsrechte (Lesen, Schreiben, Ausführen) von Dateien und Ordnern zu ändern. In Linux werden Rechte mit den Buchstaben r (read), w (write), x (execute) und mit Zahlen (chmod 755) vergeben.', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(149, 'Festplatten unterliegen unterschieldichen Einflüssen, welche sich auf die Lebensdauer von Datenträgern auswirken. Was bedeutet in diesem Zusammenhang S.M.A.R.T?', 'S.M.A.R.T. steht für Self-Monitoring, Analysis and Reporting Technology.Es ist ein Überwachungssystem für Festplatten und SSDs, das hilft, Fehler frühzeitig zu erkennen und mögliche Defekte vorherzusagen.', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen'),
(150, 'Welche Kommandos oder Werkzeugen kennst du, um unter Linux eine IPv4-Adresse eines Netzwerkadapters anzuzeigen?', 'ifconfig, ip addr show - ip a', 'Entwickeln,Erstellen und Betreuen von IT-Lösungen');

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `karten`
--
ALTER TABLE `karten`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT für exportierte Tabellen
--

--
-- AUTO_INCREMENT für Tabelle `karten`
--
ALTER TABLE `karten`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=151;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
